import datetime
from typing import Optional

from pydantic import BaseModel


class ChemicalDataBase(BaseModel):
    id: int
    formula: Optional[str]
    charge: Optional[int]
    mass: Optional[float]
    monoisotopic_mass: Optional[float]
    is_autogenerated: bool


class ChemicalData(ChemicalDataBase):
    status: "StatusBase"
    structure: "StructureBase"
    compound: "CompoundBase"


class ChemicalDataSearch(BaseModel):
    id: Optional[int] = None
    formula: Optional[str] = None
    charge: Optional[int] = None
    mass: Optional[float] = None
    monoisotopic_mass: Optional[float] = None
    is_autogenerated: Optional[bool] = None
    status_id: Optional[int] = None
    structure_id: Optional[int] = None
    compound_id: Optional[int] = None


class ChemicalDataSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[ChemicalData]


class CommentBase(BaseModel):
    text: str
    created_on: Optional[datetime.date]
    datatype: str
    datatype_id: int
    compound_id: int


class InchiBase(BaseModel):
    inchi: str
    compound_id: int


class Inchi(InchiBase):
    inchi: str
    compound: "CompoundBase"


class InchiSearch(BaseModel):
    inchi: Optional[str] = None
    compound_id: Optional[int] = None


class InchiSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Inchi]


class DatabaseAccessionBase(BaseModel):
    id: int
    accession_number: Optional[str]
    type: str


class DatabaseAccession(DatabaseAccessionBase):
    accession_number: Optional[str]
    type: str
    status: "StatusBase"
    source: "SourceBase"
    compound: "CompoundBase"


class DatabaseAccessionSearch(BaseModel):
    id: Optional[int] = None
    accession_number: Optional[str] = None
    type: Optional[str] = None
    status_id: Optional[int] = None
    source_id: Optional[int] = None
    compound_id: Optional[int] = None


class DatabaseAccessionSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[DatabaseAccession]


class NameBase(BaseModel):
    id: int
    name: Optional[str]
    type: str
    adapted: bool
    language_code: str
    ascii_name: Optional[str]


class Name(NameBase):
    compound: "CompoundBase"
    status: "StatusBase"


class NameSearch(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    type: Optional[str] = None
    adapted: Optional[bool] = None
    language_code: Optional[str] = None
    ascii_name: Optional[str] = None
    compound_id: Optional[int] = None
    status_id: Optional[int] = None


class NameSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Name]


class RelationTypeBase(BaseModel):
    id: int
    code: str
    allow_cycles: bool
    description: Optional[str]


class RelationType(RelationTypeBase):
    pass


class RelationTypeSearch(BaseModel):
    id: Optional[int] = None
    code: Optional[str] = None
    allow_cycles: Optional[bool] = None
    description: Optional[str] = None


class RelationTypeSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[RelationType]


class RelationBase(BaseModel):
    id: Optional[int]
    evidence_accession: Optional[str]
    evidence_source_id: Optional[int]
    relation_type_id: Optional[int]
    final_id: Optional[int]
    init_id: Optional[int]
    status_id: Optional[int]


class Relation(RelationBase):
    id: Optional[int]
    evidence_accession: Optional[str]
    evidence_source: Optional["SourceBase"]
    relation_type: Optional["RelationTypeBase"]
    final_compound: "CompoundBase"
    init_compound: "CompoundBase"
    status: "StatusBase"


class RelationSearch(BaseModel):
    id: Optional[int] = None
    evidence_accession: Optional[str] = None
    evidence_source_id: Optional[int] = None
    relation_type_id: Optional[int] = None
    final_id: Optional[int] = None
    init_id: Optional[int] = None
    status_id: Optional[int] = None


class RelationSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Relation]


class ReferenceBase(BaseModel):
    id: int
    location_in_ref: Optional[str]
    accession_number: Optional[str]
    reference_name: Optional[str]


class Reference(ReferenceBase):
    source: "SourceBase"
    compound: "CompoundBase"


class ReferenceSearch(BaseModel):
    id: Optional[int] = None
    location_in_ref: Optional[str] = None
    accession_number: Optional[str] = None
    reference_name: Optional[str] = None
    source_id: Optional[int] = None
    compound_id: Optional[int] = None


class ReferenceSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Reference]


class StructureBase(BaseModel):
    id: int
    smiles: Optional[str]
    standard_inchi: Optional[str]
    standard_inchi_key: Optional[str]
    dimension: str
    default_structure: bool
    compound_id: int
    status_id: int


class Structure(StructureBase):
    compound: "CompoundBase"
    status: "StatusBase"
    chemical_data: list["ChemicalDataBase"]


class StructureSearch(BaseModel):
    id: Optional[int] = None
    smiles: Optional[str] = None
    standard_inchi: Optional[str] = None
    standard_inchi_key: Optional[str] = None
    dimension: Optional[str] = None
    default_structure: Optional[bool] = None
    compound_id: Optional[int] = None
    status_id: Optional[int] = None


class StructureSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Structure]


class CompoundBase(BaseModel):
    id: int
    name: str
    source: Optional[str]
    merge_type: Optional[str]
    chebi_accession: str
    definition: Optional[str]
    ascii_name: Optional[str]
    stars: int
    modified_on: Optional[datetime.datetime]
    release_date: Optional[datetime.datetime]


class Compound(CompoundBase):
    parent_id: Optional[int]
    status: "StatusBase"
    chemical_data: list["ChemicalDataBase"]
    comments: list["CommentBase"]
    database_accessions: list["DatabaseAccessionBase"]
    names: list["NameBase"]
    references: list["ReferenceBase"]
    structures: list["StructureBase"]


class CompoundSearch(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    source: Optional[str] = None
    merge_type: Optional[str] = None
    chebi_accession: Optional[str] = None
    definition: Optional[str] = None
    ascii_name: Optional[str] = None
    stars: Optional[int] = None
    modified_on: Optional[datetime.datetime] = None
    release_date: Optional[datetime.datetime] = None
    parent_id: Optional[int] = None
    status_id: Optional[int] = None


class CompoundSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Compound]


class StatusBase(BaseModel):
    id: int
    name: str


class Status(StatusBase):
    pass


class StatusSearch(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None


class StatusSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Status]


class SourceBase(BaseModel):
    id: int
    name: str
    url: Optional[str]
    prefix: str
    description: Optional[str] = None


class Source(SourceBase):
    pass


class SourceSearch(BaseModel):
    id: Optional[int] = None
    name: Optional[str] = None
    url: Optional[str] = None
    prefix: Optional[str] = None
    description: Optional[str] = None


class SourceSearchResults(BaseModel):
    count: int
    offset: int
    limit: int
    results: list[Source]
