version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    # Use 'pip install' with the --group flag (supported in modern pip)
    install:
      - pip install .
      - pip install --group readthedocs

mkdocs:
  configuration: mkdocs.yml