"""CHEBI model definition."""

import datetime
import enum
import stat
from turtle import back
from typing import List, Optional

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class CompoundStatus(enum.Enum):
    C = "CHECKED"
    D = "DELETED"
    E = "ANNOTATED_BY_THIRD_PARTY"
    O = "OBSOLETE"
    S = "EXISTS_BUT_NOT_CHECKED"


class Base(DeclarativeBase):
    """Base class db schema."""

    pass


class Compound(Base):
    """Class definition for the chebi_compound table.

    status_id values:
    (1, 'C', 'CHECKED')
    (2, 'D', 'DELETED')
    (3, 'E', 'OK')
    (4, 'F', 'PENDING_SUBMISSION')
    (5, 'I', 'INTERNAL')
    (6, 'O', 'OBSOLETE')
    (7, 'P', 'DEPRECATED')
    (8, 'R', 'REDUNDANT')
    (9, 'S', 'SUBMITTED')

    """

    __tablename__ = "chebi_compound"
    __table_args__ = {
        "comment": "Compound",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    id: Mapped[int] = mapped_column(primary_key=True)

    name: Mapped[str] = mapped_column(Text)
    status_id: Mapped[Optional[int]] = mapped_column(ForeignKey("chebi_status.id"))
    source: Mapped[Optional[str]] = mapped_column(String(32))
    parent_id: Mapped[Optional[int]] = mapped_column(ForeignKey("chebi_compound.id"))
    merge_type: Mapped[Optional[str]] = mapped_column(String(1))
    chebi_accession: Mapped[str] = mapped_column(String(30))
    definition: Mapped[Optional[str]] = mapped_column(Text)
    ascii_name: Mapped[Optional[str]] = mapped_column(Text)
    stars: Mapped[int]
    modified_on: Mapped[Optional[datetime.date]]
    release_date: Mapped[Optional[datetime.date]]

    # Relationships
    status: Mapped[Optional["Status"]] = relationship(back_populates="compounds")

    chemical_data: Mapped[List["ChemicalData"]] = relationship(
        back_populates="compound"
    )
    comments: Mapped[List["Comment"]] = relationship(back_populates="compound")
    database_accessions: Mapped[List["DatabaseAccession"]] = relationship(
        back_populates="compound"
    )
    names: Mapped[List["Name"]] = relationship(back_populates="compound")
    references: Mapped[List["Reference"]] = relationship(back_populates="compound")
    structures: Mapped[List["Structure"]] = relationship(back_populates="compound")
    database_accessions: Mapped[List["DatabaseAccession"]] = relationship(
        back_populates="compound"
    )


class ChemicalData(Base):
    """Class definition for the chebi_chemical_data table."""

    __tablename__ = "chebi_chemical_data"
    __table_args__ = {
        "comment": "Chemical data",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)
    compound_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    formula: Mapped[Optional[str]] = mapped_column(Text)
    charge: Mapped[Optional[int]]
    mass: Mapped[Optional[float]]
    monoisotopic_mass: Mapped[Optional[float]]
    status_id: Mapped[Optional[int]] = mapped_column(ForeignKey("chebi_status.id"))
    structure_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("chebi_structure.id")
    )
    is_autogenerated: Mapped[bool]

    # Foreign key relationship
    status: Mapped[Optional["Status"]] = relationship(back_populates="chemical_data")
    structure: Mapped[Optional["Structure"]] = relationship(
        back_populates="chemical_data"
    )
    compound: Mapped[Compound] = relationship(back_populates="chemical_data")


class Comment(Base):
    """Class definition for the chebi_comment table."""

    __tablename__ = "chebi_comment"
    __table_args__ = {
        "comment": "Comment",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    compound_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    comment: Mapped[str] = mapped_column(Text)
    author_name: Mapped[Optional[str]] = mapped_column(Text)
    status_id: Mapped[int] = mapped_column(ForeignKey("chebi_status.id"))
    datatype: Mapped[str] = mapped_column(String(30))
    datatype_id: Mapped[int]

    # relationships
    compound: Mapped[Compound] = relationship(back_populates="comments")
    status: Mapped["Status"] = relationship(back_populates="comments")


class DatabaseAccession(Base):
    """Class definition for the chebi_database_accession table."""

    __tablename__ = "chebi_database_accession"
    __table_args__ = {
        "comment": "Database accession",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    compound_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    accession_number: Mapped[Optional[str]] = mapped_column(String(255))
    type: Mapped[str] = mapped_column(String(255))
    status_id: Mapped[int] = mapped_column(ForeignKey("chebi_status.id"))
    source_id: Mapped[int] = mapped_column(ForeignKey("chebi_source.id"))

    # relationships
    status: Mapped["Status"] = relationship(back_populates="database_accessions")
    source: Mapped["Source"] = relationship(back_populates="database_accessions")
    compound: Mapped[Compound] = relationship(back_populates="database_accessions")


class Name(Base):
    """Class definition for the chebi_name table."""

    __tablename__ = "chebi_name"
    __table_args__ = {
        "comment": "Name",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    compound_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    name: Mapped[str] = mapped_column(Text)
    type: Mapped[str] = mapped_column(String(255))
    status_id: Mapped[int] = mapped_column(ForeignKey("chebi_status.id"))
    adapted: Mapped[bool]
    language_code: Mapped[str] = mapped_column(String(2))
    ascii_name: Mapped[Optional[str]] = mapped_column(Text)

    # relationships
    compound: Mapped[Compound] = relationship(back_populates="names")
    status: Mapped["Status"] = relationship(back_populates="names")


class RelationType(Base):
    """Class definition for the chebi_relation_type table."""

    __tablename__ = "chebi_relation_type"
    __table_args__ = {
        "comment": "Relation Type",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    code: Mapped[str] = mapped_column(String(255))
    allow_cycles: Mapped[bool]
    description: Mapped[Optional[str]] = mapped_column(String(255))
    relations: Mapped[List["Relation"]] = relationship(back_populates="relation_type")


class Relation(Base):
    """Class definition for the chebi_relation table."""

    __tablename__ = "chebi_relation"
    __table_args__ = {
        "comment": "Relation",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    # id	relation_type_id	init_id	final_id	status_id	evidence_accession	evidence_source_id
    id: Mapped[int] = mapped_column(primary_key=True)

    relation_type_id: Mapped[int] = mapped_column(ForeignKey("chebi_relation_type.id"))
    init_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    final_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    status_id: Mapped[int] = mapped_column(ForeignKey("chebi_status.id"))
    evidence_accession: Mapped[Optional[str]] = mapped_column(String(7))
    evidence_source_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey("chebi_source.id")
    )

    # Relationships
    relation_type: Mapped[RelationType] = relationship(back_populates="relations")
    init_compound: Mapped[Compound] = relationship(foreign_keys=[init_id])
    final_compound: Mapped[Compound] = relationship(foreign_keys=[final_id])
    status: Mapped["Status"] = relationship(back_populates="relations")
    evidence_source: Mapped[Optional["Source"]] = relationship(
        back_populates="relations"
    )


class Reference(Base):
    """Class definition for the chebi_reference table."""

    __tablename__ = "chebi_reference"
    __table_args__ = {
        "comment": "Reference",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    # id	compound_id	location_in_ref	source_id	accession_number	reference_name
    id: Mapped[int] = mapped_column(primary_key=True)
    location_in_ref: Mapped[Optional[str]] = mapped_column(String(255))
    accession_number: Mapped[str] = mapped_column(String(255))
    reference_name: Mapped[Optional[str]] = mapped_column(Text)

    source_id: Mapped[int] = mapped_column(ForeignKey("chebi_source.id"))
    source: Mapped["Source"] = relationship(back_populates="references")

    compound_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    compound: Mapped[Compound] = relationship(back_populates="references")


class Structure(Base):
    """Class definition for the chebi_structure table."""

    __tablename__ = "chebi_structure"
    __table_args__ = {
        "comment": "Structure",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    id: Mapped[int] = mapped_column(primary_key=True)
    compound_id: Mapped[int] = mapped_column(ForeignKey("chebi_compound.id"))
    status_id: Mapped[int] = mapped_column(ForeignKey("chebi_status.id"))
    # molefile: Mapped[Optional[str]] = mapped_column(Text)  # currently unused
    smiles: Mapped[Optional[str]] = mapped_column(Text)
    standard_inchi: Mapped[Optional[str]] = mapped_column(Text)
    standard_inchi_key: Mapped[Optional[str]] = mapped_column(String(27))
    dimension: Mapped[str] = mapped_column(String(30))
    default_structure: Mapped[bool]

    # Foreign key relationship
    compound: Mapped[Compound] = relationship(back_populates="structures")
    status: Mapped["Status"] = relationship(back_populates="structures")
    chemical_data: Mapped[List["ChemicalData"]] = relationship(
        back_populates="structure"
    )


class Source(Base):
    """Class definition for the chebi_source table."""

    __tablename__ = "chebi_source"
    __table_args__ = {
        "comment": "Source",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    name: Mapped[str] = mapped_column(String(255))
    url: Mapped[Optional[str]] = mapped_column(String(255))
    prefix: Mapped[str] = mapped_column(String(255))
    description: Mapped[Optional[str]] = mapped_column(Text)

    # relationships
    references: Mapped[List[Reference]] = relationship(back_populates="source")
    relations: Mapped[List["Relation"]] = relationship(back_populates="evidence_source")
    database_accessions: Mapped[List[DatabaseAccession]] = relationship(
        back_populates="source"
    )


class Status(Base):
    """Class definition for the chebi_status table."""

    __tablename__ = "chebi_status"
    __table_args__ = {
        "comment": "Status",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    name: Mapped[str] = mapped_column(String(20))

    # relationships

    compounds: Mapped[List[Compound]] = relationship(back_populates="status")
    chemical_data: Mapped[List[ChemicalData]] = relationship(back_populates="status")
    relations: Mapped[List[Relation]] = relationship(back_populates="status")
    names: Mapped[List[Name]] = relationship(back_populates="status")
    database_accessions: Mapped[List[DatabaseAccession]] = relationship(
        back_populates="status"
    )
    comments: Mapped[List[Comment]] = relationship(back_populates="status")
    structures: Mapped[List[Structure]] = relationship(back_populates="status")
