"""CHEBI model definition."""

import datetime
from typing import List, Optional

from sqlalchemy import ForeignKey, Integer, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

from biokb_chebi.constants import TABLE_PREFIX


class Base(DeclarativeBase):
    """Base class db schema."""

    pass


class Compound(Base):
    """Class definition for the chebi_compound table.

    status_id values:
    (1, 'C', 'CHECKED')
    (2, 'D', 'DELETED')
    (3, 'E', 'OK')
    (4, 'F', 'PENDING_SUBMISSION')
    (5, 'I', 'INTERNAL')
    (6, 'O', 'OBSOLETE')
    (7, 'P', 'DEPRECATED')
    (8, 'R', 'REDUNDANT')
    (9, 'S', 'SUBMITTED')

    """

    __tablename__ = f"{TABLE_PREFIX}compound"
    __table_args__ = {
        "comment": "Compound",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    id: Mapped[int] = mapped_column(primary_key=True)

    name: Mapped[str] = mapped_column(Text)
    source: Mapped[Optional[str]] = mapped_column(String(32))
    merge_type: Mapped[Optional[str]] = mapped_column(String(1))
    chebi_accession: Mapped[str] = mapped_column(String(30))
    definition: Mapped[Optional[str]] = mapped_column(Text)
    ascii_name: Mapped[Optional[str]] = mapped_column(Text)
    stars: Mapped[int]
    modified_on: Mapped[Optional[datetime.datetime]]
    release_date: Mapped[Optional[datetime.datetime]]

    # foreign keys
    status_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey(f"{TABLE_PREFIX}status.id")
    )
    parent_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey(f"{TABLE_PREFIX}compound.id")
    )

    # relationships
    status: Mapped[Optional["Status"]] = relationship(back_populates="compounds")

    chemical_data: Mapped[List["ChemicalData"]] = relationship(
        back_populates="compound"
    )
    comments: Mapped[List["Comment"]] = relationship(back_populates="compound")
    database_accessions: Mapped[List["DatabaseAccession"]] = relationship(
        back_populates="compound"
    )
    names: Mapped[List["Name"]] = relationship(back_populates="compound")
    references: Mapped[List["Reference"]] = relationship(back_populates="compound")
    structures: Mapped[List["Structure"]] = relationship(back_populates="compound")

    def __repr__(self) -> str:
        """String representation of the Compound object."""
        return (
            f"<Compound(id={self.id!r}, chebi_accession={self.chebi_accession!r},"
            f" name={self.name!r})>"
        )


class ChemicalData(Base):
    """Class definition for the chebi_chemical_data table."""

    __tablename__ = f"{TABLE_PREFIX}chemical_data"
    __table_args__ = {
        "comment": "Chemical data",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)
    formula: Mapped[Optional[str]] = mapped_column(Text)
    charge: Mapped[Optional[int]]
    mass: Mapped[Optional[float]]
    monoisotopic_mass: Mapped[Optional[float]]
    is_autogenerated: Mapped[bool]

    # foreign keys
    status_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey(f"{TABLE_PREFIX}status.id")
    )
    structure_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey(f"{TABLE_PREFIX}structure.id")
    )
    compound_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))

    # relationships
    status: Mapped[Optional["Status"]] = relationship(back_populates="chemical_data")
    structure: Mapped[Optional["Structure"]] = relationship(
        back_populates="chemical_data"
    )
    compound: Mapped[Compound] = relationship(back_populates="chemical_data")

    def __repr__(self) -> str:
        """String representation of the ChemicalData object."""
        return (
            f"<ChemicalData(id={self.id!r}, formula={self.formula!r},"
            f" mass={self.mass!r}, charge={self.charge!r})>"
        )


class Comment(Base):
    """Class definition for the chebi_comment table."""

    __tablename__ = f"{TABLE_PREFIX}comment"
    __table_args__ = {
        "comment": "Comment",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    comment: Mapped[str] = mapped_column(Text)
    author_name: Mapped[Optional[str]] = mapped_column(Text)
    datatype: Mapped[str] = mapped_column(String(30))
    datatype_id: Mapped[int]

    # foreign keys
    compound_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))
    status_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}status.id"))

    # relationships
    compound: Mapped[Compound] = relationship(back_populates="comments")
    status: Mapped["Status"] = relationship(back_populates="comments")

    def __repr__(self) -> str:
        """String representation of the Comment object."""
        return f"<Comment(id={self.id!r}, datatype={self.datatype!r}, comment={self.comment!r})>"


class DatabaseAccession(Base):
    """Class definition for the chebi_database_accession table."""

    __tablename__ = f"{TABLE_PREFIX}database_accession"
    __table_args__ = {
        "comment": "Database accession",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    accession_number: Mapped[Optional[str]] = mapped_column(String(255))
    type: Mapped[str] = mapped_column(String(255))

    # foreign keys
    status_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}status.id"))
    source_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}source.id"))
    compound_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))

    # relationships
    status: Mapped["Status"] = relationship(back_populates="database_accessions")
    source: Mapped["Source"] = relationship(back_populates="database_accessions")
    compound: Mapped[Compound] = relationship(back_populates="database_accessions")

    def __repr__(self) -> str:
        """String representation of the DatabaseAccession object."""
        return (
            f"<DatabaseAccession(id={self.id!r}, type={self.type!r},"
            f" accession_number={self.accession_number!r})>"
        )


class Name(Base):
    """Class definition for the chebi_name table."""

    __tablename__ = f"{TABLE_PREFIX}name"
    __table_args__ = {
        "comment": "Name",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    name: Mapped[Optional[str]] = mapped_column(Text)
    type: Mapped[str] = mapped_column(String(255))
    adapted: Mapped[bool]
    language_code: Mapped[str] = mapped_column(String(2))
    ascii_name: Mapped[Optional[str]] = mapped_column(Text)

    # foreign keys
    compound_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))
    status_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}status.id"))

    # relationships
    compound: Mapped[Compound] = relationship(back_populates="names")
    status: Mapped["Status"] = relationship(back_populates="names")

    def __repr__(self) -> str:
        """String representation of the Name object."""
        return f"<Name(id={self.id!r}, type='{self.type!r}'," f" name='{self.name!r}')>"


class RelationType(Base):
    """Class definition for the chebi_relation_type table."""

    __tablename__ = f"{TABLE_PREFIX}relation_type"
    __table_args__ = {
        "comment": "Relation Type",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    code: Mapped[str] = mapped_column(String(255))
    allow_cycles: Mapped[bool]
    description: Mapped[Optional[str]] = mapped_column(String(255))

    # relationships
    relations: Mapped[List["Relation"]] = relationship(back_populates="relation_type")

    def __repr__(self) -> str:
        """String representation of the RelationType object."""
        return f"<RelationType(id={self.id!r}, code='{self.code!r}')>"


class Relation(Base):
    """Class definition for the chebi_relation table."""

    __tablename__ = f"{TABLE_PREFIX}relation"
    __table_args__ = {
        "comment": "Relation",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    id: Mapped[int] = mapped_column(primary_key=True)
    evidence_accession: Mapped[Optional[str]] = mapped_column(String(7))

    # foreign keys
    evidence_source_id: Mapped[Optional[int]] = mapped_column(
        ForeignKey(f"{TABLE_PREFIX}source.id")
    )
    relation_type_id: Mapped[int] = mapped_column(
        ForeignKey(f"{TABLE_PREFIX}relation_type.id")
    )
    init_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))
    final_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))
    status_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}status.id"))

    # Relationships
    relation_type: Mapped[Optional[RelationType]] = relationship(
        back_populates="relations"
    )
    init_compound: Mapped[Compound] = relationship(foreign_keys=[init_id])
    final_compound: Mapped[Compound] = relationship(foreign_keys=[final_id])
    status: Mapped["Status"] = relationship(back_populates="relations")
    evidence_source: Mapped[Optional["Source"]] = relationship(
        back_populates="relations"
    )

    def __repr__(self) -> str:
        """String representation of the Relation object."""
        return (
            f"<Relation(id={self.id!r}, init_id={self.init_id!r},"
            f" final_id={self.final_id!r}, relation_type_id={self.relation_type_id!r})>"
        )


class Reference(Base):
    """Class definition for the chebi_reference table."""

    __tablename__ = f"{TABLE_PREFIX}reference"
    __table_args__ = {
        "comment": "Reference",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    id: Mapped[int] = mapped_column(primary_key=True)
    location_in_ref: Mapped[Optional[str]] = mapped_column(String(255))
    accession_number: Mapped[str] = mapped_column(String(255))
    reference_name: Mapped[Optional[str]] = mapped_column(Text)

    # foreign keys
    source_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}source.id"))
    compound_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))

    # relationships
    source: Mapped["Source"] = relationship(back_populates="references")
    compound: Mapped[Compound] = relationship(back_populates="references")

    def __repr__(self) -> str:
        """String representation of the Reference object."""
        return (
            f"<Reference(id={self.id!r}, accession_number='{self.accession_number!r}',"
            f" reference_name='{self.reference_name!r}')>"
        )


class Structure(Base):
    """Class definition for the chebi_structure table."""

    __tablename__ = f"{TABLE_PREFIX}structure"
    __table_args__ = {
        "comment": "Structure",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }
    id: Mapped[int] = mapped_column(primary_key=True)

    smiles: Mapped[Optional[str]] = mapped_column(Text)
    standard_inchi: Mapped[Optional[str]] = mapped_column(Text)
    standard_inchi_key: Mapped[Optional[str]] = mapped_column(String(27))
    dimension: Mapped[str] = mapped_column(String(30))
    default_structure: Mapped[bool]

    # foreign keys
    compound_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}compound.id"))
    status_id: Mapped[int] = mapped_column(ForeignKey(f"{TABLE_PREFIX}status.id"))

    # relationships
    compound: Mapped[Compound] = relationship(back_populates="structures")
    status: Mapped["Status"] = relationship(back_populates="structures")
    chemical_data: Mapped[List["ChemicalData"]] = relationship(
        back_populates="structure"
    )

    # molefile: Mapped[Optional[str]] = mapped_column(Text)  # currently unused

    def __repr__(self) -> str:
        """String representation of the Structure object."""
        return (
            f"<Structure(id={self.id!r}, standard_inchi_key='{self.standard_inchi_key!r}',"
            f" dimension='{self.dimension!r}')>"
        )


class Source(Base):
    """Class definition for the chebi_source table."""

    __tablename__ = f"{TABLE_PREFIX}source"
    __table_args__ = {
        "comment": "Source",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    name: Mapped[str] = mapped_column(String(255))
    url: Mapped[Optional[str]] = mapped_column(String(255))
    prefix: Mapped[str] = mapped_column(String(255))
    description: Mapped[Optional[str]] = mapped_column(Text)

    # relationships
    references: Mapped[List[Reference]] = relationship(back_populates="source")
    relations: Mapped[List["Relation"]] = relationship(back_populates="evidence_source")
    database_accessions: Mapped[List[DatabaseAccession]] = relationship(
        back_populates="source"
    )

    def __repr__(self) -> str:
        """String representation of the Source object."""
        return (
            f"<Source(id={self.id!r}, name='{self.name!r}', prefix='{self.prefix!r}')>"
        )


class Status(Base):
    """Class definition for the chebi_status table."""

    __tablename__ = f"{TABLE_PREFIX}status"
    __table_args__ = {
        "comment": "Status",
        "mysql_charset": "utf8",
        "mysql_collate": "utf8_unicode_ci",
    }

    id: Mapped[int] = mapped_column(primary_key=True)

    name: Mapped[str] = mapped_column(String(20))

    # relationships

    compounds: Mapped[List[Compound]] = relationship(back_populates="status")
    chemical_data: Mapped[List[ChemicalData]] = relationship(back_populates="status")
    relations: Mapped[List[Relation]] = relationship(back_populates="status")
    names: Mapped[List[Name]] = relationship(back_populates="status")
    database_accessions: Mapped[List[DatabaseAccession]] = relationship(
        back_populates="status"
    )
    comments: Mapped[List[Comment]] = relationship(back_populates="status")
    structures: Mapped[List[Structure]] = relationship(back_populates="status")

    def __repr__(self) -> str:
        """String representation of the Status object."""
        return f"<Status(id={self.id!r}, name='{self.name!r}')>"
